[tox]
envlist = mypy,pre-commit,py,twinecheck

[testenv]
deps =
    pytest-cov>=7.1.0
    pytest>=9.0
commands =
    pytest --cov=xtractmime \
        --cov-report=term-missing --cov-report=xml \
        {posargs: xtractmime tests}

[testenv:mypy]
basepython = python3
deps =
    mypy==1.20.2
    pytest==9.1.1
commands =
    mypy {posargs: xtractmime tests}

[testenv:pre-commit]
basepython = python3
deps =
    pre-commit
commands =
    pre-commit run {posargs:--all-files}

[testenv:twinecheck]
basepython = python3
deps =
    twine==6.2.0
    build==1.5.1
commands =
    python -m build --sdist
    twine check dist/*
